# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: ../src/Controller/
    type: attribute
admin_teacher_index:
    path: /admin/teacher
    controller: App\Controller\Admin\TeacherController::index
    methods: GET

admin_teacher_edit:
    path: /admin/teacher/{id}/edit
    controller: App\Controller\Admin\TeacherController::edit
    methods: [GET, POST]

admin_teacher_delete:
    path: /admin/teacher/{id}
    controller: App\Controller\Admin\TeacherController::delete
    methods: POST
